############################################################################### 
# 
# Makefile for a script (e.g. Python) Assembler project 
# 
# Students: 
# Amit Silber, ID 204630537, amit.silber@mail.huji.ac.il 
# Daniel Neimark, ID 204128656, daniel.neimark@mail.huji.ac.il 
# 
############################################################################### 
 
# The executable for projects 6 is Assembler, so make sure the running  
# environment can execute it by changing permissions using chmod. 
# Obviously, your project may be more complicated and require a different  
# makefile. 
 
all: 
	chmod a+x JackCompiler
	chmod a+x JackAnalyzer.py
	chmod a+x ClassParser.py
	chmod a+x ExpressionParser.py
	chmod a+x JackTokenizer.py
	chmod a+x LexicalWriter.py
	chmod a+x StatementsParser.py
	chmod a+x Symbol.py
	chmod a+x SymbolTable.py
	chmod a+x VMWriter.py