###############################################################################
#
# Makefile for a script (e.g. Python) Assembler project
#
# Students:
# Amit Silber, ID 204630537, amit.silber@mail.huji.ac.il
# Daniel Neimark, ID 204128656, daniel.neimark@mail.huji.ac.il
#
###############################################################################

# The executable for projects 6 is Assembler, so make sure the running 
# environment can execute it by changing permissions using chmod.
# Obviously, your project may be more complicated and require a different 
# makefile.

all:
	chmod a+x Assembler
	chmod a+x Assembler.py
	chmod a+x AInstruction.py
	chmod a+x CCommandParser.py
	chmod a+x CommentHandler.py
	chmod a+x FileReader.py
	chmod a+x FileSaver.py
	chmod a+x JumpStatements.py
	chmod a+x VariableAllocator.py
	chmod a+x WhiteSpaceHandler.py
