############################################################################### 
# 
# Makefile for a script (e.g. Python) Assembler project 
# 
# Students: 
# Amit Silber, ID 204630537, amit.silber@mail.huji.ac.il 
# Daniel Neimark, ID 204128656, daniel.neimark@mail.huji.ac.il 
# 
############################################################################### 
 
# The executable for projects 6 is Assembler, so make sure the running  
# environment can execute it by changing permissions using chmod. 
# Obviously, your project may be more complicated and require a different  
# makefile. 
 
all: 
	chmod a+x VMtranslator 
	chmod a+x VMtranslator.py 
	chmod a+x Addition.py 
	chmod a+x ArgumentParser.py 
	chmod a+x BasicArithmeticOp.py 
	chmod a+x BinaryAnd.py 
	chmod a+x BinaryOr.py 
	chmod a+x BootStrap.py 
	chmod a+x CommentHandler.py 
	chmod a+x ConditionsOp.py 
	chmod a+x ConstantParser.py 
	chmod a+x EqualOp.py 
	chmod a+x FileReader.py 
	chmod a+x FileSaver.py 
	chmod a+x GTop.py 
	chmod a+x LocalParser.py 
	chmod a+x LTop.py 
	chmod a+x Negation.py 
	chmod a+x Not.py 
	chmod a+x OneOperandArithmetic.py 
	chmod a+x PointerParser.py 
	chmod a+x PushPopParser.py 
	chmod a+x StaticParser.py 
	chmod a+x Subtraction.py 
	chmod a+x TempParser.py 
	chmod a+x ThatParser.py 
	chmod a+x ThisParser.py 
	chmod a+x FunctionCallParser.py 
	chmod a+x FunctionDecParser.py 
	chmod a+x FunctionRetParser.py 
	chmod a+x GotoParser.py 
	chmod a+x IfGoTo.py 
	chmod a+x LabelParser.py 